server:
  port: ${serverPort:443}
  use-forward-headers: true
  ssl:
    key-store: ${keystoreLocation}
    key-store-password: ${keystorePassword}
    key-password: ${keystorePassword}
    key-alias: ${keystoreSSLKey:tomcat}

rserve:
  host: ${rserveHost}
  port: ${rservePort:6311}
  user: ${rserveUser:}
  password: ${rservePassword:}
  timeout:
    ms: ${rserveTimeout:120000}
  retry:
    interval:
      ms: ${rserveRetryInterval:5000}

security:
  require-ssl: true
  basic:
    enabled: false

management:
  security:
    enabled: false

spring:
  profiles:
    active: default, swagger
  application:
    name: aqcu-java-to-r
  jmx:
    default-domain: aqcu-java-to-r
